[project]
name = "remote-lab"
version = "0.1.0"
description = "CREATOR remote lab server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "requests>=2.32.5",
]
